code4romania/war-support-sprijin-de-urgenta-client

components/FormEntryButton/FormEntryButton.tsx, pages/index.tsx, styles/globals.css
Additional styling to home component and buttons
Closes #28
=> (feat) Home Component additional styling

.github/workflows/deploy-prod.yml
=> add step to invalidate cf distribution

components/Form/Checkbox.tsx, components/Form/Dropdown.tsx, components/Form/Radio.tsx, components/Form/Textarea.tsx
Added dropdown form component
https://github.com/code4romania/war-support-sprijin-de-urgenta-client/issues/33
=> Form components: Dropdown

components/Form/Checkbox.tsx, components/Form/Date.tsx, components/Form/Input.tsx, components/Form/Number.tsx, components/Form/Radio.tsx, components/Form/Textarea.tsx, components/Form/common.tsx, pages/form-elements.tsx, pages/index.tsx
* Added Date and Number field types
* Extracted common components
https://github.com/code4romania/war-support-sprijin-de-urgenta-client/issues/33
=> Form components: Date, Number, Misc

components/Form/Dropdown.tsx, pages/form-elements.tsx
Update dropdown component to reuse same components as the other inputs
https://github.com/code4romania/war-support-sprijin-de-urgenta-client/issues/33
=> Form components: Add support for errors to dropdown component

components/Header/Header.tsx, components/Header/LanguageSelector.tsx, next-env.d.ts, pages/index.tsx, store/index.ts, store/reducers/locale/index.ts
[Closes #35  ](https://github.com/code4romania/war-support-sprijin-de-urgenta-client/issues/35)
=> Added LanguageSelector component, hooked it to redux and i18n

.storybook/main.js, .storybook/preview.js, components/Button/Button.stories.tsx, components/Form/Checkbox.stories.tsx, components/Form/Date.stories.tsx, components/Form/Dropdown.stories.tsx, components/Form/Input.stories.tsx, components/Form/Number.stories.tsx, components/Form/Radio.stories.tsx, components/Form/Textarea.stories.tsx, components/Header/Header.stories.tsx, components/Image/Image.stories.tsx, components/Layout/Layout.stories.tsx, generate_component/index.js, generate_component/story_template.js, package.json
=> Add Storybook

package-lock.json, package.json
=> Add webpack5 as dev dependency to fix storybook

.storybook/i18next.js, .storybook/main.js, .storybook/preview.js, components/Button/Button.stories.tsx, components/Form/Checkbox.stories.tsx, components/Form/Date.stories.tsx, components/Form/Dropdown.stories.tsx, components/Form/Input.stories.tsx, components/Form/Number.stories.tsx, components/Form/Radio.stories.tsx, components/Form/Textarea.stories.tsx, components/Header/Header.stories.tsx, generate_component/story_template.js, package-lock.json, package.json, store/index.ts
=> Add storybook-react-i18next addon

components/Form/Dropdown.tsx, components/UserTypeForm/UserTypeForm.tsx, components/UserTypeForm/index.ts, pages/steps.tsx, public/locales/en/common.json, public/locales/ro/common.json, store/reducers/signup/index.ts, store/reducers/steps/index.ts, store/reducers/steps/index.tsx, store/reducers/steps/types.ts
Closes #15
* create redux action for setting the user type
* create user type component
* add an extra option for the dropdown component (which is hidden and disabled)
=> Create User Type Component for Sign Up page.

components/UserTypeForm/UserTypeForm.tsx, pages/steps.tsx, store/reducers/steps/types.ts, store/types/state.type.ts, tsconfig.json
=> Add '@/store' alias in tsconfig.json

components/Form/Radio.tsx, components/SignUpResources/SignUpResources.tsx, components/SignUpResources/index.ts, components/SignupVolunteering/CheckboxWithDescription.tsx, pages/form-elements.tsx, public/locales/ro/common.json
=> Sign Up - Resources

hooks/useData.ts, package-lock.json, package.json, pages/_app.tsx, pages/index.tsx, pages/register.tsx
=> Add SWR and fetch data on homepage

.env, components/SignUpResources/SignUpResources.tsx
https://github.com/code4romania/war-support-sprijin-de-urgenta-client/issues/76
=> Fix env api link

pages/_app.tsx
=> Remove request refresh interval

components/SignUpResources/SignUpResources.tsx, pages/index.tsx, store/index.ts, store/reducers/categories/index.ts, store/reducers/categories/types.ts, store/reducers/signup/index.ts, store/types/state.type.ts
=> Hardcode categories

components/Button/Button.tsx, components/Button/IconButton.tsx, components/Dialog/Dialog.stories.tsx, components/Dialog/Dialog.tsx, components/Dialog/index.ts, components/Dialog/styles.module.css, components/Footer/Footer.tsx, components/Form/Dropdown.tsx, components/Layout/Layout.tsx, components/SignUpResources/SignUpResources.tsx, components/SignUpServicesForm/SignUpServicesFormWithModal.tsx, components/SignUpServicesForm/index.ts, package-lock.json, package.json, public/locales/ro/common.json, styles/globals.css
Implements modal with Reach Dialog. A JSX element can be passed to it. Still needs some minor css adjustments
Closes #55
Buttons for opening forms
Modal in desktop view (needs some styling in the jsx component)
Modal in mobile view (needs to take full screen; too tired right now)
=> Implement Reach Dialog for adding Resources

components/UserCredentials/UserCredentials.tsx, components/UserDetails/UserDetails.tsx, store/reducers/signup/index.ts
=> fixes a ts error

components/UserCredentials/UserCredentials.tsx
=> fixes an undefined error

components/Header/Header.tsx
=> Fix header duplicated import

hooks/useAppDispatch.tsx, pages/login.tsx, store/reducers/auth/index.ts
=> Redirect login on success and show error when fails

components/Footer/Footer.tsx, components/Form/Checkbox.tsx, components/Form/CheckboxGroup.tsx, components/Form/Dropdown.tsx, components/Form/Radio.tsx, components/Form/RadioGroup.tsx, components/Header/Header.tsx, components/Layout/Layout.tsx, components/SignUpResources/SignUpResources.tsx, components/SignUpServicesForm/SignUpServicesForm.tsx, components/SignUpServicesForm/SignUpServicesFormWithModal.tsx, components/SignupVolunteering/CheckboxWithDescription.tsx, components/SignupVolunteering/index.tsx, components/StepperButton/StepperButton.tsx, pages/_app.tsx, pages/index.tsx, pages/login.tsx, pages/services.tsx, pages/sign-up/index.tsx
- small refactors (remove not needed clsx, remove double footer, refactored sign up to use an object instead of switch)
- format some files
=> small refactors and format

pages/sign-up/index.tsx
When the user is authenticated, the stepper was still on the user type step instead of the last one.
This offers a quick and easy fix for this issue.
Verified that the stepper works properly regardless of auth status.
=> Quick fix for wrong step being displayed

api/types.ts, forms/TransportGoodsForm.tsx, forms/TransportPersonsForm.tsx
=> County choices quick fix. Transport Type changed

components/Dialog/styles.module.css, styles/globals.css
Styles the scrollbar globally and inside modal 
Closes #124
=> Scrollbar Global Styles

forms/TransportGoodsForm.tsx
https://github.com/code4romania/war-support-sprijin-de-urgenta-client/issues/119
Closes #119
=> use car number regex & error

components/Stepper/StepperItem.tsx, components/StepperButton/StepperButtonGroup.tsx, components/UserCredentials/UserCredentials.tsx, components/UserDetails/UserDetails.tsx, components/UserTypeForm/UserTypeForm.tsx, pages/index.tsx, pages/sign-up/index.tsx
=> Styling enhancements based on figma design

components/CallToAction/CallToAction.stories.tsx, components/CallToAction/CallToAction.tsx, pages/index.tsx, pages/offer.tsx, pages/request.tsx
=> CallToAction url prop for button action

components/Dialog/Dialog.tsx, components/Dialog/styles.module.css, components/SignUpServicesForm/SignUpServicesFormWithModal.tsx
Add title to Dialog. 
Closes #128
=> Add title to modal

components/Button/Button.tsx, components/SignUpServicesForm/SignUpServicesFormWithModal.tsx, forms/TransportGoodsForm.tsx, forms/TransportPersonsForm.tsx, public/locales/ro/common.json
Fixed CSS on services form buttons
Added className to Button component
Added validation rule for availability
Closes #XXX
=> Small adjustments to services form

components/Form/Dropdown.tsx, components/UserTypeForm/UserTypeForm.tsx, public/locales/ro/common.json
=> Fix dropdown

.env, components/Button/Button.tsx, components/SignUpServicesForm/SignUpServicesFormWithModal.tsx, forms/TransportGoodsForm.tsx, forms/TransportPersonsForm.tsx, hooks/useData.ts, public/locales/ro/common.json
=> API base url is now adjusted based on the current selected language

components/OtherResourcesForm/OtherResourcesForm.tsx, components/SignupVolunteering/index.tsx
=> Fix yup import

components/SignupPage/SignupPage.tsx, components/UserCredentials/UserCredentials.tsx, pages/sign-up/offer.tsx, pages/sign-up/request.tsx
Nu stiu daca e bug sau nu, dar:
- daca intri si vrei sa mergi pe flowul de offer (nu ai cont)…si mergi si selectezi user type, apoi pui nume si telefon, apoi creezi emal/password esti redirectat catre
router.push('/request/resources')
ar trebui sa tinem cont si sa fie redirect catre /offer/resources?
daca nu e bug, pot sterge pr-ul :D
=> redirect to "/offer/resources" for offer flow

components/SignUpProducts/index.tsx
Fixes #161
- needs more styling;
- dropdowns needs to be populated;
- extract categories from backend;
Closes #XXX
=> Implement Products with Modal Component

components/Form/Checkbox.tsx, components/GdprConsent/Consent.stories.tsx, components/GdprConsent/Consent.tsx, components/GdprConsent/index.ts, components/UserCredentials/UserCredentials.tsx, public/locales/ro/common.json
=> Added consent button to sign-up form

api/types.ts, components/Form/DropdownMultiSelect.tsx, components/Form/types.ts, components/SignUpResources/SignUpResources.tsx, components/SignUpServicesForm/SignUpServicesForm.tsx, components/SignUpServicesForm/index.ts, forms/TransportGoodsForm.tsx, forms/TransportPersonsForm.tsx, public/locales/ro/common.json, utils/regexes.ts
- Integrated multi select dropdown with react hook form
- Added multi select dropdown to both goods and persons form
- Updated regexes for car plate and id card to ignore case
Closes #166
=> Services form update

components/SignUpProducts/BuildingMaterials.tsx, components/SignUpProducts/Form.tsx, components/SignUpProducts/GenericProduct.tsx, components/SignUpProducts/Tents.tsx, components/SignUpProducts/TextileProduct.tsx, components/SignUpProducts/common/Location.tsx, components/SignUpProducts/common/Product.tsx, components/SignUpProducts/common/Quantity.tsx, components/SignUpProducts/index.tsx, components/SignUpProducts/types.ts, public/locales/ro/common.json
=> Update products counties_coverage

.github/workflows/deploy-prod.yml
=> add upload to s3

components/ResourcesTableList/ResourcesTableList.stories.tsx
=> fix story for build

components/ResourcesTableList/ResourceTableItem.tsx, components/ResourcesTableList/ResourcesTableList.tsx, components/SignUpProducts/BuildingMaterials.tsx, components/SignUpProducts/Form.tsx, components/SignUpProducts/GenericProduct.tsx, components/SignUpProducts/Tents.tsx, components/SignUpProducts/TextileProduct.tsx, components/SignUpProducts/index.tsx, components/SignUpServicesForm/SignUpServicesForm.tsx, forms/TransportGoodsForm.tsx, pages/login.tsx, public/locales/ro/common.json
=> Resources table

components/SignUpResources/SignUpResources.tsx
=> Add StepperButtonGroup to SignUpResources

components/ResourcesTableList/ResourcesTableList.stories.tsx
=> Fix ResourcesTable storybook args

forms/TransportGoodsForm.tsx, forms/TransportPersonsForm.tsx
=> Fix radio button for transport services

components/Form/DropdownMultiSelect.tsx
=> Add select all option in DropdownMultiSelect Component

components/SignUpProducts/Form.tsx, components/SignUpProducts/Others.tsx, components/SignUpProducts/index.tsx, components/SignUpProducts/types.ts, public/locales/ro/common.json
=> Add name and description to Product Other

components/ResourcesForm/ResourcesForm.stories.tsx
=> Fix types for ResourcesForm story

components/Footer/Footer.tsx, components/Form/DropdownMultiSelect.tsx, components/Form/Input.tsx, components/OtherResourcesForm/OtherResourcesForm.tsx, components/ResourcesForm/ResourcesForm.tsx, components/SignUpProducts/Tents.tsx, components/SignUpProducts/common/ProductTypeWrapper.tsx, components/SignUpProducts/index.tsx, components/SignUpResources/SignUpResources.tsx, components/SignUpServicesForm/SignUpServicesForm.tsx, components/SignupVolunteering/index.tsx, components/StepperButton/StepperButtonGroup.tsx
- Use same heading on all form sections
- Tables are hidden by default
- Table are on right on large screens, on bottom on small screens
Closes #121
=> Forms Standardization 

api/types.ts, components/OtherResourcesForm/OtherResourcesForm.tsx, components/SignupVolunteering/Dialog.tsx, components/SignupVolunteering/index.tsx, public/locales/ro/common.json
=> Add resource table to Volunteering

components/Form/DropdownMultiSelect.tsx
=> Fixed error console from DropdownMultiSelect

api/types.ts, components/OtherResourcesForm/OtherResourcesForm.tsx, components/ResourcesForm/ResourcesForm.tsx, components/SignUpProducts/index.tsx, components/SignUpResources/SignUpResources.tsx, components/SignUpServicesForm/SignUpServicesForm.tsx, components/SignupVolunteering/Dialog.tsx, components/SignupVolunteering/index.tsx, pages/_app.tsx
=> Move form states to resources form

api/types.ts, components/OtherResourcesForm/Dialog.tsx, components/SignupVolunteering/Dialog.tsx
=> added available_until default value

components/Form/Checkbox.tsx, components/Form/Date.tsx, components/Form/Dropdown.tsx, components/Form/DropdownMultiSelect.tsx, components/Form/Input.tsx, components/Form/Number.tsx, components/Form/Radio.tsx, components/Form/RadioGroup.tsx, components/Form/Textarea.tsx, components/Form/common.tsx, components/Form/types.ts, components/GdprConsent/Consent.tsx, components/SignUpResources/SignUpResources.tsx, components/UserCredentials/UserCredentials.tsx, components/UserDetails/UserDetails.tsx, components/UserTypeForm/UserTypeForm.tsx
Inputs required asterisk
Closes #XXX
=> required asterisks for all input fields

forms/request/transport/RequestTransportGoodsForm.tsx, forms/request/transport/RequestTransportPersonsForm.tsx
Fixes #234
TODO Fix labels to show From To instead of just County
=> Adapt Request Forms - Services

api/types.ts, forms/request/transport/RequestTransportGoodsForm.tsx, forms/request/transport/RequestTransportPersonsForm.tsx, public/locales/ro/common.json
=> Update request transport labels

api/types.ts, components/SignUpResources/SignUpResources.tsx, components/SignUpServicesForm/SignUpServicesForm.tsx, forms/request/transport/RequestTransportGoodsForm.tsx, forms/request/transport/RequestTransportPersonsForm.tsx
=> Update request transports

components/Header/Header.tsx
=> Update login button

components/SignUpResources/SignUpResources.tsx
=> Submit requested resources

.env.production
=> Remove production endpoint for Olivia's demo

forms/offer/transport/OfferTransportGoodsForm.tsx, forms/offer/transport/OfferTransportPersonsForm.tsx
when no value selected for type a weird message appears
=> Fix wrong validation message

api/types.ts, components/SignUpProducts/index.tsx, components/SignUpResources/SignUpResources.tsx, forms/offer/products/OfferTents.tsx, forms/offer/products/OfferTextileProduct.tsx
=> Remove unused mandatory fields for OfferTent and OfferTextile

components/SignUpResources/SignUpResources.tsx
=> Remove resources when submit is successful

forms/offer/transport/OfferTransportGoodsForm.tsx, forms/offer/transport/OfferTransportPersonsForm.tsx
=> Fix offer transport people form

components/SignUpProducts/index.tsx, forms/common/Location.tsx, forms/offer/products/OfferProductsOthers.tsx
=> Update offer products other

forms/common/Quantity.tsx, forms/offer/products/OfferProductsOthers.tsx
=> Fix offer products others

components/SignUpProducts/index.tsx, forms/common/Location.tsx, forms/offer/products/OfferBuildingMaterials.tsx, forms/offer/products/OfferGenericProduct.tsx, forms/offer/products/OfferProductsOthers.tsx, forms/offer/products/OfferTents.tsx, forms/offer/products/OfferTextileProduct.tsx, forms/request/products/RequestGenericProduct.tsx
=> Add category for all Products Resources

components/SignUpResources/SignUpResources.tsx
=> Submit form on add item for Request Resources

forms/offer/transport/OfferTransportGoodsForm.tsx, forms/offer/transport/OfferTransportPersonsForm.tsx, public/locales/en/common.json, public/locales/ro/common.json, public/locales/ru/common.json, public/locales/ua/common.json, scripts/translate/JSON_Translations.csv
Fix for https://github.com/code4romania/war-support-sprijin-de-urgenta-client/issues/273
availability drop-down should be required
Closes #273
=> #273-availability-should-be-required

forms/offer/volunteering/OfferVolunteeringForm.tsx
=> [Volunteering] add has_transportation field to volunteering forms

forms/offer/others/OfferOthersForm.tsx, forms/offer/volunteering/OfferVolunteeringForm.tsx
use ```gap-4``` instead of ```space-x-4``` tailwind class
closes #277
=> spacing between Judet & Oras

components/Form/Date.tsx, components/Form/Dropdown.tsx, components/Form/DropdownMultiSelect.tsx, components/Form/Input.tsx, components/Form/Number.tsx, components/Form/Textarea.tsx, components/Form/common.tsx
Closes #272 
@cipick this is the new PR
=> remove hasError from Label

forms/offer/products/OfferTents.tsx, forms/request/products/RequestTents.tsx, public/locales/en/common.json, public/locales/ro/common.json, public/locales/ru/common.json, public/locales/ua/common.json
- use persons unit as placeholder
- added yup validation rules
Closes #286
=> use persons unit as placeholder

forms/offer/others/OfferOthersForm.tsx, forms/offer/products/OfferBuildingMaterials.tsx, forms/offer/products/OfferGenericProduct.tsx, forms/validators.ts, public/locales/ro/common.json
closes #281
closes #283
closes #282 
closes #279
closes #278
=> Add date validations

components/UserCredentials/UserCredentials.tsx
=> add phone number to registration

api/types.ts, components/SignUpResources/SignUpResources.tsx
=> Send 'made_by' key for requests

.env.production
=> update prod api url

api/types.ts, components/SignUpResources/SignUpResources.tsx
=> merge to main

components/UserTypeForm/UserTypeForm.tsx
=> Fix dropdown on usertype

.github/workflows/deploy-stag.yml
=> specify dev env explicitly

.github/workflows/deploy-stag.yml
=> set api url explicitly

components/Header/Header.tsx, env/.env.development, env/.env.production, env/.env.staging, utils/envVars.ts
=> Get login url from env variables

components/UserDetails/UserDetails.tsx
=> Remove phone number from UserDetails

forms/offer/products/OfferBuildingMaterials.tsx
=> Fix offer building materials

components/Header/Header.tsx
=> Use small gov logo on mobile

forms/request/volunteering/RequestVolunteeringForm.tsx
=> Fix RequestVolunteeringForm

api/types.ts, forms/offer/products/OfferTextileProduct.tsx, public/locales/ro/common.json
=> rework textile form

components/OtherResourcesForm/OtherResourcesForm.tsx, forms/request/others/RequestOthersForm.tsx
=> Fix request other resources form

forms/request/others/RequestOthersForm.tsx
=> Fix error messages for Request other forms

components/GTagScript/GTagScript.tsx, components/GTagScript/index.ts, env/.env.development, env/.env.production, env/.env.staging, package-lock.json, package.json, pages/_app.tsx, tsconfig.json, utils/gtag.ts
=> Add GTag script

pages/_app.tsx
=> Remove cookie if user is not found

pages/_app.tsx
Fix going back bug when navigating unauthenticated
Closes #350
=> replace route when redirecting

components/Form/Checkbox.tsx, components/Form/Date.tsx, components/Form/Dropdown.tsx, components/Form/Input.tsx, components/Form/Number.tsx, components/Form/Radio.tsx, components/Form/Textarea.tsx, components/UserCredentials/UserCredentials.tsx, forms/common/ExpireDate.tsx, forms/offer/others/OfferOthersForm.tsx, forms/offer/products/OfferBuildingMaterials.tsx, forms/offer/products/OfferGenericProduct.tsx, forms/offer/products/OfferProductsOthers.tsx, forms/offer/products/OfferTents.tsx, forms/offer/products/OfferTextileProduct.tsx, forms/offer/transport/OfferTransportGoodsForm.tsx, forms/offer/transport/OfferTransportPersonsForm.tsx, forms/offer/volunteering/OfferVolunteeringForm.tsx, forms/request/others/RequestOthersForm.tsx, forms/request/transport/RequestTransportGoodsForm.tsx, forms/request/transport/RequestTransportPersonsForm.tsx, forms/request/volunteering/RequestVolunteeringForm.tsx
- pass required prop to show the red asterisk for required fields (I believe some are dynamic...will create another ticket for those)
- remove required native html prop to avoid native validation
Closes #298
=> pass required as prop

components/SignUpProducts/index.tsx, forms/index.ts, forms/offer/products/OfferMedicine.tsx, forms/offer/products/OfferSanitaryMaterials.tsx, forms/request/products/RequestMedicine.tsx, forms/request/products/RequestSanitaryMaterials.tsx, public/locales/en/common.json, public/locales/ro/common.json, public/locales/ru/common.json, public/locales/uk/common.json
=> Add medicine & Sanitary materials forms

.github/workflows/deploy-stag.yml
=> force stag deploy

forms/common/Location.tsx, forms/common/Product.tsx, forms/common/Quantity.tsx, forms/offer/products/OfferMedicine.tsx, forms/offer/products/OfferSanitaryMaterials.tsx, forms/request/products/RequestBuildingMaterials.tsx, forms/request/products/RequestGenericProduct.tsx, forms/request/products/RequestLocation.tsx, forms/request/products/RequestMedicine.tsx, forms/request/products/RequestOthers.tsx, forms/request/products/RequestSanitaryMaterials.tsx, forms/request/products/RequestTents.tsx, forms/request/products/RequestTextileProduct.tsx
=> Update medicine and sanitary forms

utils/regexes.ts
=> Update phone regex

forms/common/Quantity.tsx, forms/request/products/RequestBuildingMaterials.tsx, forms/request/products/RequestGenericProduct.tsx, forms/request/products/RequestMedicine.tsx, forms/request/products/RequestOthers.tsx, forms/request/products/RequestSanitaryMaterials.tsx, forms/request/products/RequestTents.tsx, forms/request/products/RequestTextileProduct.tsx
=> Update quantity to optional for request items

components/UserCredentials/UserCredentials.tsx
- Use ```setError``` from react hook form to update field error instead of adding it to local state after failed request
- Also formatted the file
Closes #267
=> use seError method instead

components/MainPage/MainPage.tsx, store/index.ts, store/reducers/categories/index.ts, store/reducers/categories/types.ts, store/reducers/foodform/index.ts, store/reducers/foodform/types.ts, store/types/state.type.ts
=> feat: add button link
